import type { Template } from "@/types/workflow.types";

// NOTE: The 'id' field will be generated by Firestore upon creation.
// These are definitions used for seeding the database.

export const preInstalledTemplates: Omit<Template, 'id'>[] = [];
