import type { Template } from './types';

// NOTE: The 'id' field will be generated by Firestore upon creation.
// These are definitions used for seeding the database.

export const preInstalledTemplates: Omit<Template, 'id'>[] = [
  // 1. Basic Template: "Solicitud de Vacaciones"
  {
    name: "Solicitud de Vacaciones",
    description: "Un flujo de trabajo simple para solicitar y aprobar tiempo libre.",
    fields: [
      { id: 'field-start-date', label: 'Fecha de Inicio', type: 'date', options: [] },
      { id: 'field-end-date', label: 'Fecha de Fin', type: 'date', options: [] },
      { id: 'field-reason', label: 'Motivo del Permiso', type: 'textarea', options: [] }
    ],
    steps: [
      { id: 'step-manager-approval', name: 'Aprobación del Gerente', type: 'task', assigneeRole: 'Manager', slaHours: 24, outcomes: ['Aprobado', 'Rechazado'] },
      { id: 'step-hr-confirmation', name: 'Confirmación de RRHH', type: 'task', assigneeRole: 'Recursos Humanos', slaHours: 48 },
      { id: 'step-payroll-update', name: 'Actualización de Nómina', type: 'task', assigneeRole: 'Nómina', slaHours: 72 }
    ],
    pools: [{
      id: 'pool-main', name: 'Proceso de Vacaciones',
      lanes: [{
        id: 'lane-main', name: 'Actores',
        steps: [
          { id: 'step-manager-approval', name: 'Aprobación del Gerente', type: 'task', assigneeRole: 'Manager', slaHours: 24, outcomes: ['Aprobado', 'Rechazado'] },
          { id: 'step-hr-confirmation', name: 'Confirmación de RRHH', type: 'task', assigneeRole: 'Recursos Humanos', slaHours: 48 },
          { id: 'step-payroll-update', name: 'Actualización de Nómina', type: 'task', assigneeRole: 'Nómina', slaHours: 72 }
        ]
      }]
    }],
    rules: [
        {
            id: 'rule-vacation-approved',
            condition: { fieldId: 'step-manager-approval', operator: '==', value: 'Aprobado', type: 'outcome' },
            action: { type: 'ROUTE_TO_STEP', stepId: 'step-hr-confirmation' }
        }
    ]
  },
  // 2. Intermediate Template: "Solicitud de Compra"
  {
    name: "Solicitud de Compra",
    description: "Flujo de trabajo para la adquisición de bienes o servicios con aprobación condicional.",
    fields: [
      { id: 'field-item-desc', label: 'Descripción del Artículo', type: 'text', options: [] },
      { id: 'field-quantity', label: 'Cantidad', type: 'number', options: [] },
      { id: 'field-cost', label: 'Costo Estimado (USD)', type: 'number', options: [] },
      { id: 'field-justification', label: 'Justificación', type: 'textarea', options: [] }
    ],
    steps: [
      { id: 'step-dept-head-approval', name: 'Aprobación Jefe de Depto.', type: 'task', assigneeRole: 'Manager', slaHours: 24, outcomes: ['Aprobado', 'Rechazado'] },
      { id: 'step-finance-review', name: 'Revisión Financiera', type: 'task', assigneeRole: 'Finanzas', slaHours: 48 },
      { id: 'step-procurement', name: 'Adquisición', type: 'task', assigneeRole: 'Compras', slaHours: 72 }
    ],
    pools: [{
      id: 'pool-proc', name: 'Proceso de Compra',
      lanes: [{
        id: 'lane-proc', name: 'Aprobadores',
        steps: [
          { id: 'step-dept-head-approval', name: 'Aprobación Jefe de Depto.', type: 'task', assigneeRole: 'Manager', slaHours: 24, outcomes: ['Aprobado', 'Rechazado'] },
          { id: 'step-finance-review', name: 'Revisión Financiera', type: 'task', assigneeRole: 'Finanzas', slaHours: 48 },
          { id: 'step-procurement', name: 'Adquisición', type: 'task', assigneeRole: 'Compras', slaHours: 72 }
        ]
      }]
    }],
    rules: [
      {
        id: 'rule-cost-check',
        condition: { fieldId: 'field-cost', operator: '>', value: 5000, type: 'form' },
        action: { type: 'REQUIRE_ADDITIONAL_STEP', stepId: 'step-finance-review' }
      },
      {
        id: 'rule-purchase-approved',
        condition: { fieldId: 'step-dept-head-approval', operator: '==', value: 'Aprobado', type: 'outcome' },
        action: { type: 'ROUTE_TO_STEP', stepId: 'step-procurement' }
      }
    ]
  },
  // 3. Complex Template: "Incidente de Soporte de TI"
  {
    name: "Incidente de Soporte de TI",
    description: "Proceso complejo para la gestión y resolución de tickets de soporte técnico entre diferentes equipos.",
    fields: [
      { id: 'field-category', label: 'Categoría del Problema', type: 'select', options: ['Hardware', 'Software', 'Red', 'Cuenta de Usuario'] },
      { id: 'field-urgency', label: 'Urgencia', type: 'radio', options: ['Alta', 'Media', 'Baja'] },
      { id: 'field-description-detail', label: 'Descripción Detallada', type: 'textarea', options: [] },
      { id: 'field-attachment', label: 'Adjuntar Captura de Pantalla', type: 'file', options: [] }
    ],
    steps: [
      { id: 'step-triage', name: 'Clasificación Inicial', type: 'task', assigneeRole: 'Soporte N1', outcomes: ['Resolver y Cerrar', 'Escalar a N2', 'Enviar a Redes'], slaHours: 1 },
      { id: 'step-advanced-analysis', name: 'Análisis Avanzado', type: 'task', assigneeRole: 'Soporte N2', slaHours: 8 },
      { id: 'step-network-review', name: 'Revisión de Red', type: 'task', assigneeRole: 'Infraestructura', slaHours: 8 },
      { id: 'step-user-confirmation', name: 'Confirmación del Usuario', type: 'task', assigneeRole: 'Submitter', slaHours: 24 }
    ],
    pools: [
      { id: 'pool-ti', name: 'Departamento de TI', lanes: [
        { id: 'lane-l1', name: 'Soporte Nivel 1', steps: [
            { id: 'step-triage', name: 'Clasificación Inicial', type: 'task', assigneeRole: 'Soporte N1', outcomes: ['Resolver y Cerrar', 'Escalar a N2', 'Enviar a Redes'], slaHours: 1 }
        ]},
        { id: 'lane-l2', name: 'Soporte Nivel 2', steps: [
            { id: 'step-advanced-analysis', name: 'Análisis Avanzado', type: 'task', assigneeRole: 'Soporte N2', slaHours: 8 }
        ]},
        { id: 'lane-infra', name: 'Infraestructura', steps: [
            { id: 'step-network-review', name: 'Revisión de Red', type: 'task', assigneeRole: 'Infraestructura', slaHours: 8 }
        ]}
      ]},
      { id: 'pool-user', name: 'Usuario Final', lanes: [
        { id: 'lane-submitter', name: 'Solicitante', steps: [
             { id: 'step-user-confirmation', name: 'Confirmación del Usuario', type: 'task', assigneeRole: 'Submitter', slaHours: 24 }
        ]}
      ]}
    ],
    rules: [
      { id: 'rule-route-n2', condition: { fieldId: 'step-triage', operator: '==', value: 'Escalar a N2', type: 'outcome' }, action: { type: 'ROUTE_TO_STEP', stepId: 'step-advanced-analysis' } },
      { id: 'rule-route-net', condition: { fieldId: 'step-triage', operator: '==', value: 'Enviar a Redes', type: 'outcome' }, action: { type: 'ROUTE_TO_STEP', stepId: 'step-network-review' } },
      { id: 'rule-set-priority', condition: { fieldId: 'field-urgency', operator: 'is', value: 'Alta', type: 'form' }, action: { type: 'CHANGE_REQUEST_PRIORITY', priority: 'Alta' } }
    ]
  }
];
