
const NOW = new Date().toISOString();

export const SEED_ROLES = [
    {
        id: 'role-admin',
        name: 'Administrador',
        description: 'Acceso total al sistema',
        isSystemRole: true,
        permissions: [
            { module: 'dashboard', level: 'write' },
            { module: 'users', level: 'write' },
            { module: 'roles', level: 'write' },
            { module: 'admin_roles', level: 'write' },
            { module: 'hcm_employees', level: 'write' },
            { module: 'hcm_attendance', level: 'write' },
            { module: 'hcm_incidences', level: 'write' },
            { module: 'hcm_prenomina', level: 'write' },
            { module: 'hcm_calendar', level: 'write' },
            { module: 'hcm_org_chart', level: 'write' },
            { module: 'hcm_talent_grid', level: 'write' },
        ],
        createdAt: NOW,
        updatedAt: NOW,
    },
    {
        id: 'role-hr-manager',
        name: 'Gerente de RH',
        description: 'Gestión completa de Capital Humano',
        isSystemRole: true,
        permissions: [
            { module: 'dashboard', level: 'read' },
            { module: 'requests', level: 'write' },
            { module: 'hcm_employees', level: 'write' },
            { module: 'hcm_attendance', level: 'write' },
            { module: 'hcm_incidences', level: 'write' },
            { module: 'hcm_prenomina', level: 'write' },
            { module: 'hcm_calendar', level: 'write' },
            { module: 'hcm_org_chart', level: 'read' },
            { module: 'hcm_talent_grid', level: 'write' },
        ],
        createdAt: NOW,
        updatedAt: NOW,
    },
    {
        id: 'role-supervisor',
        name: 'Supervisor',
        description: 'Aprobación de incidencias de su equipo',
        isSystemRole: false,
        permissions: [
            { module: 'dashboard', level: 'read' },
            { module: 'requests', level: 'write' },
            { module: 'hcm_employees', level: 'read' },
            { module: 'hcm_incidences', level: 'write' },
            { module: 'hcm_calendar', level: 'read' },
        ],
        createdAt: NOW,
        updatedAt: NOW,
    },
    {
        id: 'role-employee',
        name: 'Colaborador',
        description: 'Acceso básico para empleados',
        isSystemRole: true,
        permissions: [
            { module: 'dashboard', level: 'read' },
            { module: 'requests', level: 'write' },
            { module: 'hcm_calendar', level: 'read' },
        ],
        createdAt: NOW,
        updatedAt: NOW,
    },
];

export const SEED_LOCATIONS_STRUCT = [
    {
        id: 'loc-corporativo-gdl',
        name: 'Corporativo Guadalajara',
        code: 'CORP-GDL',
        type: 'corporativo',
        address: 'Av. Américas 1500, Col. Providencia',
        city: 'Guadalajara',
        state: 'Jalisco',
        overtimeResetDay: 'sunday',
        toleranceMinutes: 10,
        useVirtualCheckIn: true,
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
        createdById: 'admin-user',
    },
    {
        id: 'loc-cedis-gdl',
        name: 'CEDIS Guadalajara',
        code: 'CEDIS-GDL',
        type: 'cedis',
        address: 'Periférico Sur 8500, Zona Industrial',
        city: 'Tlajomulco',
        state: 'Jalisco',
        overtimeResetDay: 'sunday',
        toleranceMinutes: 5,
        useVirtualCheckIn: false,
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
        createdById: 'admin-user',
    },
    {
        id: 'loc-tienda-centro',
        name: 'Tienda Centro',
        code: 'T-001',
        type: 'tienda',
        address: 'Av. Juárez 200, Centro',
        city: 'Guadalajara',
        state: 'Jalisco',
        overtimeResetDay: 'saturday',
        toleranceMinutes: 5,
        useVirtualCheckIn: false,
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
        createdById: 'admin-user',
    },
];

export const SEED_DEPARTMENTS = [
    {
        id: 'dept-direccion',
        name: 'Dirección General',
        code: 'DIR',
        description: 'Dirección ejecutiva de la empresa',
        managerId: 'emp-director-general',
        parentDepartmentId: null,
        costCenter: 'CC-100',
        budget: 500000,
        budgetPeriod: 'annual',
        locationId: 'loc-corporativo-gdl',
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
        createdById: 'admin-user',
    },
    {
        id: 'dept-rh',
        name: 'Recursos Humanos',
        code: 'RH',
        description: 'Gestión de Capital Humano',
        managerId: 'emp-gerente-rh',
        parentDepartmentId: 'dept-direccion',
        costCenter: 'CC-200',
        budget: 150000,
        budgetPeriod: 'annual',
        locationId: 'loc-corporativo-gdl',
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
        createdById: 'admin-user',
    },
    {
        id: 'dept-operaciones',
        name: 'Operaciones',
        code: 'OPS',
        description: 'Operaciones y logística',
        managerId: 'emp-gerente-operaciones',
        parentDepartmentId: 'dept-direccion',
        costCenter: 'CC-300',
        budget: 300000,
        budgetPeriod: 'annual',
        locationId: 'loc-cedis-gdl',
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
        createdById: 'admin-user',
    },
    {
        id: 'dept-administracion',
        name: 'Administración',
        code: 'ADM',
        description: 'Administración y finanzas',
        managerId: 'emp-gerente-admin',
        parentDepartmentId: 'dept-direccion',
        costCenter: 'CC-400',
        budget: 200000,
        budgetPeriod: 'annual',
        locationId: 'loc-corporativo-gdl',
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
        createdById: 'admin-user',
    },
    {
        id: 'dept-tecnologia',
        name: 'Tecnología',
        code: 'TI',
        description: 'Sistemas y tecnología de información',
        managerId: 'emp-gerente-ti',
        parentDepartmentId: 'dept-direccion',
        costCenter: 'CC-500',
        budget: 250000,
        budgetPeriod: 'annual',
        locationId: 'loc-corporativo-gdl',
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
        createdById: 'admin-user',
    },
];

export const SEED_POSITIONS = [
    // Dirección
    {
        id: 'pos-director-general', name: 'Director General', code: 'DG-001',
        department: 'Dirección', departmentId: 'dept-direccion', level: 1,
        canApproveOvertime: true, canApproveIncidences: true,
        approvalLimits: { expenses: 500000, purchases: 500000, travel: 200000, contracts: 500000, vacationDays: 30, overtimeHours: 50, headcount: 10 },
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    // Gerencias
    {
        id: 'pos-gerente-rh', name: 'Gerente de Recursos Humanos', code: 'GRH-001',
        department: 'Recursos Humanos', departmentId: 'dept-rh', level: 2,
        canApproveOvertime: true, canApproveIncidences: true,
        approvalLimits: { expenses: 100000, purchases: 50000, travel: 50000, contracts: 100000, vacationDays: 15, overtimeHours: 20, headcount: 3 },
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    {
        id: 'pos-gerente-operaciones', name: 'Gerente de Operaciones', code: 'GOP-001',
        department: 'Operaciones', departmentId: 'dept-operaciones', level: 2,
        canApproveOvertime: true, canApproveIncidences: true,
        approvalLimits: { expenses: 100000, purchases: 75000, travel: 30000, contracts: 50000, vacationDays: 15, overtimeHours: 30, headcount: 5 },
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    {
        id: 'pos-gerente-admin', name: 'Gerente de Administración', code: 'GAD-001',
        department: 'Administración', departmentId: 'dept-administracion', level: 2,
        canApproveOvertime: true, canApproveIncidences: true,
        approvalLimits: { expenses: 150000, purchases: 100000, travel: 50000, contracts: 150000, vacationDays: 15, overtimeHours: 15, headcount: 3 },
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    {
        id: 'pos-gerente-ti', name: 'Gerente de TI', code: 'GTI-001',
        department: 'Tecnología', departmentId: 'dept-tecnologia', level: 2,
        canApproveOvertime: true, canApproveIncidences: true,
        approvalLimits: { expenses: 100000, purchases: 200000, travel: 40000, contracts: 100000, vacationDays: 15, overtimeHours: 25, headcount: 2 },
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    // Supervisores/Coordinadores
    {
        id: 'pos-coord-rh', name: 'Coordinador de RH', code: 'CRH-001',
        department: 'Recursos Humanos', departmentId: 'dept-rh', level: 3,
        canApproveOvertime: false, canApproveIncidences: true,
        approvalLimits: { expenses: 25000, purchases: 10000, travel: 10000, vacationDays: 10, overtimeHours: 9 },
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    {
        id: 'pos-super-almacen', name: 'Supervisor de Almacén', code: 'SAL-001',
        department: 'Operaciones', departmentId: 'dept-operaciones', level: 3,
        canApproveOvertime: true, canApproveIncidences: true,
        approvalLimits: { expenses: 15000, purchases: 5000, vacationDays: 5, overtimeHours: 15 },
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    {
        id: 'pos-super-tienda', name: 'Supervisor de Tienda', code: 'STI-001',
        department: 'Operaciones', departmentId: 'dept-operaciones', level: 3,
        canApproveOvertime: true, canApproveIncidences: true,
        approvalLimits: { expenses: 10000, purchases: 3000, vacationDays: 5, overtimeHours: 10 },
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    // Analistas/Especialistas
    {
        id: 'pos-analista-rh', name: 'Analista de RH', code: 'ARH-001',
        department: 'Recursos Humanos', departmentId: 'dept-rh', level: 4,
        canApproveOvertime: false, canApproveIncidences: false,
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    {
        id: 'pos-contador', name: 'Contador', code: 'CNT-001',
        department: 'Administración', departmentId: 'dept-administracion', level: 4,
        canApproveOvertime: false, canApproveIncidences: false,
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    {
        id: 'pos-desarrollador', name: 'Desarrollador de Software', code: 'DEV-001',
        department: 'Tecnología', departmentId: 'dept-tecnologia', level: 4,
        canApproveOvertime: false, canApproveIncidences: false,
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    // Operativos
    {
        id: 'pos-almacenista', name: 'Almacenista', code: 'ALM-001',
        department: 'Operaciones', departmentId: 'dept-operaciones', level: 5,
        canApproveOvertime: false, canApproveIncidences: false,
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    {
        id: 'pos-vendedor', name: 'Vendedor', code: 'VEN-001',
        department: 'Operaciones', departmentId: 'dept-operaciones', level: 5,
        canApproveOvertime: false, canApproveIncidences: false,
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    {
        id: 'pos-auxiliar-admin', name: 'Auxiliar Administrativo', code: 'AUX-001',
        department: 'Administración', departmentId: 'dept-administracion', level: 5,
        canApproveOvertime: false, canApproveIncidences: false,
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
    {
        id: 'pos-recepcion', name: 'Recepcionista', code: 'REC-001',
        department: 'Administración', departmentId: 'dept-administracion', level: 5,
        canApproveOvertime: false, canApproveIncidences: false,
        isActive: true, createdAt: NOW, updatedAt: NOW
    },
];

export const SEED_SHIFTS_STRUCT = [
    {
        id: 'shift-oficina',
        name: 'Turno Oficina',
        code: 'OFI-01',
        type: 'diurnal',
        startTime: '09:00',
        endTime: '18:00',
        breakStartTime: '14:00',
        breakEndTime: '15:00',
        breakMinutes: 60,
        workDays: [1, 2, 3, 4, 5],
        restDays: [0, 6],
        dailyHours: 8,
        weeklyHours: 40,
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
    },
    {
        id: 'shift-almacen-matutino',
        name: 'Turno Almacén Matutino',
        code: 'ALM-MAT',
        type: 'diurnal',
        startTime: '06:00',
        endTime: '14:00',
        breakMinutes: 30,
        workDays: [1, 2, 3, 4, 5, 6],
        restDays: [0],
        dailyHours: 8,
        weeklyHours: 48,
        locationId: 'loc-cedis-gdl',
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
    },
    {
        id: 'shift-almacen-vespertino',
        name: 'Turno Almacén Vespertino',
        code: 'ALM-VES',
        type: 'mixed',
        startTime: '14:00',
        endTime: '22:00',
        breakMinutes: 30,
        workDays: [1, 2, 3, 4, 5, 6],
        restDays: [0],
        dailyHours: 8,
        weeklyHours: 48,
        locationId: 'loc-cedis-gdl',
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
    },
    {
        id: 'shift-tienda',
        name: 'Turno Tienda',
        code: 'TIE-01',
        type: 'diurnal',
        startTime: '10:00',
        endTime: '19:00',
        breakMinutes: 60,
        workDays: [1, 2, 3, 4, 5, 6],
        restDays: [0],
        dailyHours: 8,
        weeklyHours: 48,
        isActive: true,
        createdAt: NOW,
        updatedAt: NOW,
    },
];
